name: windows

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "zed-industries/zed"
          ref: ${{ github.event.inputs.branch }}

      # Fix https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md#build-fails-path-too-long
      - run: git config --system core.longpaths true
      - run: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - run: cargo build --release

      - run: gh release create ${{ github.event.inputs.branch }} -t "${{ github.event.inputs.branch }}" -R ${{ github.repository }}

      - run: gh release upload ${{ github.event.inputs.branch }} target/release/zed.exe -R ${{ github.repository }}
