name: windows

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "zed-industries/zed"
          ref: ${{ github.event.inputs.branch }}

      - run: cargo --version
